application: shakespy
version: 1
runtime: python27
api_version: 1
threadsafe: true # TODO: check if mapreduce is threadsafe

handlers:
- url: /css
  static_dir: css

- url: /.*
  script: controller.application

includes:
- mapreduce/include.yaml


